sudo: false
language: node_js
node_js:
  - 'iojs'
  - '0.12'
  - '0.10'

before_script:
  - npm install -g grunt-cli istanbul

script:
  - grunt

after_script:
  - istanbul cover ./node_modules/grunt-mocha-cli/node_modules/mocha/bin/_mocha --report lcovonly -- -R spec 'test/**/*.js'
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
